# Generated by Django 5.2.6 on 2025-10-24 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text="Enter the employee's full name.", max_length=255)),
                ('email', models.EmailField(help_text='Enter a valid and unique email address.', max_length=255, unique=True)),
                ('phone', models.CharField(help_text="Enter the employee's phone number.", max_length=15)),
                ('designation', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Tester', 'Tester')], default='Developer', help_text="Select the employee's job title.", max_length=20)),
                ('department', models.CharField(choices=[('MS', 'MS'), ('NonMS', 'NonMS')], default='NonMS', help_text="Select the employee's department.", max_length=20)),
                ('salary', models.IntegerField(help_text="Enter the employee's salary. Must be a non-negative number.", validators=[django.core.validators.MinValueValidator(0)])),
                ('dateofjoining', models.DateField(help_text='Enter the date the employee joined.')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text="Select the employee's status.", max_length=20)),
                ('address', models.TextField(help_text="Enter the employee's full address.")),
            ],
        ),
    ]
